[package]
# Don't change the package's name. Duat depends on it.
name = "config"
version = "1.0.0"
edition = "2024"
# Please don't post your configuration crate to crates.io.
# If you want to keep it somewhere, try a repository website,
# like github or gitlab
publish = false

[lib]
crate-type = ["dylib"]

[lints.clippy]
# This is useful to shorten hook declarations, so you can wrap everything in Ok.
# You can get rid of this if you wish to.
unit_arg = "allow"

[profile.release]
split-debuginfo = "unpacked"
incremental = true
lto = "off"

[dependencies.duat]
git = "https://github.com/AhoyISki/duat"
version = "0.7.4"

# Same with this one, it just adds more colorschemes.
[dependencies.duat-catppuccin]
git = "https://github.com/AhoyISki/duat-catppuccin"
version = "0.3.1"
