[patch."https://github.com/AhoyISki/duat".duat-core]
path = "../duat/duat-core/"

[patch."https://github.com/AhoyISki/duat".duat-base]
path = "../duat/duat-base/"

[patch."https://github.com/AhoyISki/duat-treesitter".duat-treesitter]
path = "../duat-treesitter/"

[patch."https://github.com/AhoyISki/duat-filetype".duat-filetype]
path = "../duat-filetype/"
